### ISSUE TITLE
10.2 Leveling Module Error

### ISSUE THREAD

**Issue by Kyreaper** [NumyAddon/TalentLoadoutManager#11]
11-25-2023 -

**Addon Version**
1.2.3

Game Version: 10.2.0.52188, Retail, US, English 

I am getting the following error on characters I am leveling. Insofar as I can tell this seems to happen whenever I get a level on my alts. I have not had a chance to try & replicate the error, but I noticed it at the end of a play session after leveling an alt. I do see the Accountant Classic addon listed numerous times in the error text, but I am not sure if this is a conflict between addons or something else.

```
1x ...aceTalentLoadoutManager/modules/Leveling.lua:44: attempt to index local 'loadoutInfo' (a nil value)
[string "@TalentLoadoutManager/modules/Leveling.lua"]:44: in function `ReapplyLoadout'
[string "@TalentLoadoutManager/modules/Leveling.lua"]:35: in function <...aceTalentLoadoutManager/modules/Leveling.lua:34>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 RawHookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:394
 Printf = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 ReapplyLoadout = <function> defined @TalentLoadoutManager/modules/Leveling.lua:40
 GetName = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "TalentLoadoutManager_Leveling"
 baseName = "TalentLoadoutManager"
 IsEnabled = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @TalentLoadoutManager/modules/Leveling.lua:57
 DisableModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 AddToCombatLockdownQueue = <function> defined @TalentLoadoutManager/modules/Leveling.lua:49
 PLAYER_LEVEL_UP = <function> defined @TalentLoadoutManager/modules/Leveling.lua:27
 OnDisable = <function> defined @TalentLoadoutManager/modules/Leveling.lua:23
 OnEnable = <function> defined @TalentLoadoutManager/modules/Leveling.lua:19
 RegisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 HookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:365
 Print = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 CombatLockdownQueue = <table> {
 }
 IsHooked = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:492
 GetArgs = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 RegisterChatCommand = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 IsModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleState = true
 SetDefaultModuleState = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 UnregisterAllEvents = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 SendMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 SetEnabledState = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 UnregisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterEvent = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 hooks 
 ```
 
 The following screenshots are from BugGrabber / BugSack:
 
![11-25-2023 TalentLoadoutManager Leveling Module Error (1)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/7504edab-69e7-48a7-a5ec-8c33ce4702a1)
![11-25-2023 TalentLoadoutManager Leveling Module Error (2)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/c1437527-ab86-4b1f-96e1-ba6ef0906781)
![11-25-2023 TalentLoadoutManager Leveling Module Error (3)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/40892dc7-6cfb-4d14-9a3d-ddab06eb70ac)
![11-25-2023 TalentLoadoutManager Leveling Module Error (4)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/9e8742e2-78f8-4246-8df8-5518d17c4629)

**Comment by Numynum** [comment]
hi, could you write this in chat, and send me what it says?
`/run local a=TalentLoadoutManagerAPI;local l=a.CharacterAPI:GetActiveLoadoutID();print(l, a.GlobalAPI:GetLoadoutInfoByID(l))`
on characters you're leveling on, and seeing this error with, are you using a specific loadout? or using blizzard's recommended path?

**Comment by Kyreaper** [comment]
I tried your script on my main first (not seeing the error on that char) & it returned:
17397192 table: 00000270270F3720

I tried your script on one of the alts I had the error on & it returned:
908312 nil

I tried your script on a couple other alts I'm leveling as well & the initial number string varied, but all returned "nil" for the second string.

The characters I was leveling & seeing the error with actually don't have any specified loadouts. 
Said characters were using Blizzards default recommended path & most only have partial points allocated or no points allocated at all. 
I have been using passive leveling methods for them & haven't played most of my alts since the DF pre-patch in SL, so most of their trees have been automatically reset by Blizzard over time.

**Comment by Kyreaper** [comment]
Good news, I was able to reproduce the error.

I logged into my leveling alts today to finish the WoW Anniversary daily in the Caverns of Time & leveled on four separate characters (from lvl 15 - 16). In each case I received the same error & was able to reproduce it exactly.

1. I logged into my lvling alt.
2. I ran your script & took a few before screenshots.
3. I did the WoW Anniversary daily & leveled from 15 - 16 on turn-in.
4. I received the error immediately upon leveling.

**The following are screenshots from before the error. The first screenshot is after running the script you provided:**

![11-27-2023 TalentLoadoutManager Error (1)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/ddb8757d-7bb7-4d0d-ba84-7b90123dea15)
![11-27-2023 TalentLoadoutManager Error (2)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/731f40e8-33c3-44c5-8f55-1a9af03a9d9a)
![11-27-2023 TalentLoadoutManager Error (3)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/8acdb0d7-f4c5-45fa-abdf-ab71a978d3bc)

**Comment by Kyreaper** [comment]
**The error text from a few minutes ago:**

3x ...aceTalentLoadoutManager/modules/Leveling.lua:44: attempt to index local 'loadoutInfo' (a nil value)
[string "@TalentLoadoutManager/modules/Leveling.lua"]:44: in function `ReapplyLoadout'
[string "@TalentLoadoutManager/modules/Leveling.lua"]:35: in function <...aceTalentLoadoutManager/modules/Leveling.lua:34>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 RawHookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:394
 Printf = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 ReapplyLoadout = <function> defined @TalentLoadoutManager/modules/Leveling.lua:40
 GetName = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "TalentLoadoutManager_Leveling"
 baseName = "TalentLoadoutManager"
 IsEnabled = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @TalentLoadoutManager/modules/Leveling.lua:57
 DisableModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 AddToCombatLockdownQueue = <function> defined @TalentLoadoutManager/modules/Leveling.lua:49
 PLAYER_LEVEL_UP = <function> defined @TalentLoadoutManager/modules/Leveling.lua:27
 OnDisable = <function> defined @TalentLoadoutManager/modules/Leveling.lua:23
 OnEnable = <function> defined @TalentLoadoutManager/modules/Leveling.lua:19
 RegisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 HookScript = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:365
 Print = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 CombatLockdownQueue = <table> {
 }
 IsHooked = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:492
 GetArgs = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 RegisterChatCommand = <function> defined @Accountant_Classic/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 IsModule = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleState = true
 SetDefaultModuleState = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 UnregisterAllEvents = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 SendMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 SetEnabledState = <function> defined @Accountant_Classic/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 UnregisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterEvent = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 hooks 
 
 ~
 
 **The following are screenshots from after the error occurred again. The first screenshot is after running the script you provided:**

![11-27-2023 TalentLoadoutManager Error (4)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/09fb6c4b-fee5-42a6-9d79-0af5be0d858d)
![11-27-2023 TalentLoadoutManager Error (5)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/8637724f-e856-4d94-8e06-ac11761b24f8)
![11-27-2023 TalentLoadoutManager Error (6)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/a61a9963-61dc-4677-a617-213e4821c6c1)
![11-27-2023 TalentLoadoutManager Error (7)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/dc847630-c8d3-4429-8e9a-10133bf1bf78)
![11-27-2023 TalentLoadoutManager Error (8)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/921ab91b-2631-4727-8e8b-df3621efd883)
![11-27-2023 TalentLoadoutManager Error (9)](https://github.com/NumyAddon/TalentLoadoutManager/assets/12869693/e310e3f2-b338-4943-a298-3e73e6cd8a5b)

**Comment by Numynum** [comment]
yeah, I see that I didn't handle the situation when someone is using the default leveling build, I'll have a look ^^

**Comment by Numynum** [comment]
should be fixed in next version
