### ISSUE TITLE
[Manager API] LoadLoadouts not working on blizzard loadouts that are used as a base

### ISSUE THREAD

**Issue by derfloh205** [NumyAddon/TalentLoadoutManager#12]
I wanted to use the API of TLM for my addon but it seems that the LoadLoadout call does not work on a blizzard loadout that has TLM loadout children? Is this intended?

I fetch a loadout I want to load and apply and then run the following
(loadout name matches in print and I use loadoutInfo.id to get the id, loadout is a blizzard loadout)

`TalentLoadoutManagerAPI.CharacterAPI:LoadLoadout(5260323, true)`

When its called for a blizzard loadout or TLM loadout it works but for a blizzard loadout that as TLM children, nothing happens

**Comment by Numynum** [comment]
Handled on discord
