### ISSUE TITLE
Change color of the selection Loadout bar.

### ISSUE THREAD

**Issue by Odysseas68** [NumyAddon/TalentLoadoutManager#13]
Hi, first of all thanks for this addon. I would like to ask for an QoL if it is possible:
The color of the selection bar in sidebar is set to dark grey and with the black background it's difficult to see what loadout i have select. Is it possible to change it to a lighter color so i can clearly see the selection i have? Or maybe in the config to put a color picker for the background/bar/font color or i suppose the easiest way to put some presets (some QoL ideas).

Thanks

**Comment by Numynum** [comment]
I've added a bunch of color pickers in the latest version 🙂
