### ISSUE TITLE
Feature Request : Auto change Loadout

### ISSUE THREAD

**Issue by gaveer** [NumyAddon/TalentLoadoutManager#14]
Hi @Numynum   i wouldl like to request a Feature that allow auto switch loadout if the target name matchthe loadout name 
we can add restriction like  in raid  , not incombat
there a weakaura for defualt blizrd loadout auto switch to get the idea 
https://wago.io/UDjtHst0Y/1

i try  to adapt it for the addon use the API but i failed .
Thank you in advance

**Comment by Numynum** [comment]
hi, [LoadoutReminder](https://www.curseforge.com/wow/addons/loadoutreminder) sounds close enough to what you're looking for, it supports both default loadouts, and TLM loadouts
I don't plan on creating similar support myself, but if you want to do this yourself, and have specific questions around the API, I can try and help with some explanations
