### ISSUE TITLE
Elemental Shaman Leveling from Icy Veins doesn't load correctly - Duplicated named "Stormkeeper"

### ISSUE THREAD

**Issue by Lilyheart** [NumyAddon/TalentLoadoutManager#18]
[Icy Veins leveling page](https://www.icy-veins.com/wow/elemental-shaman-leveling-guide) 

[Icy Veins leveling spec](https://www.icy-veins.com/wow/dragonflight-talent-calculator#7--262$ba1mipo1lOvxxMPPkABBCCD1Qj0HHhUTL1EE+he0d0cij1kglmIwx1Bssf1vNBF1LEED0aab1HG*)

Stormkeeper appears to be the problem.  The top one is in the calculator but the addon is attempting to apply the bottom one.

<img width="404" alt="stormkeeper" src="https://github.com/NumyAddon/TalentLoadoutManager/assets/383918/f2ada6d6-2e34-46bf-82d6-acfa1e7d7ccb">

You can test it with this level 36 spec:  [Icy Veins link](https://www.icy-veins.com/wow/dragonflight-talent-calculator#7--262$a1bilmo1pvxxMOPP+cd0e0ghij1klwx1Im*)

**Comment by Numynum** [comment]
interesting issue, should be fixed in next update (you'll have to import it again though)
