### ISSUE TITLE
"Script ran too long" when importing or selecting saved loadouts (CONFLICT WITH OTHER ADDONS)

### ISSUE THREAD

**Issue by MechaZao** [NumyAddon/TalentLoadoutManager#21]
hi there so this is a strange error that I have worked hard to narrow down and be able to duplicate.

`2x ...s/TalentLoadoutManager/core/TalentLoadoutManager.lua:952: script ran too long
[string "@TalentLoadoutManager/core/TalentLoadoutManager.lua"]:952: in function `PurchaseOrderedEntries'
[string "@TalentLoadoutManager/core/TalentLoadoutManager.lua"]:936: in function `PurchaseLoadoutEntryInfo'
[string "@TalentLoadoutManager/core/TalentLoadoutManager.lua"]:868: in function `ResetAndPurchaseLoadoutEntries'
[string "@TalentLoadoutManager/core/TalentLoadoutManager.lua"]:810: in function <...s/TalentLoadoutManager/core/TalentLoadoutManager.lua:726>
[string "=(tail call)"]: ?
[string "@TalentLoadoutManager/modules/DefaultUISidebar.lua"]:78: in function `DoLoad'
[string "@TalentLoadoutManager/modules/SideBarMixin.lua"]:847: in function `OnElementClick'
[string "@TalentLoadoutManager/modules/SideBarMixin.lua"]:637: in function <TalentLoadoutManager/modules/SideBarMixin.lua:635>
`

I get this error when I try to select a saved loadout OR import a new one. The game lags for ~15 seconds and then comes back with an error and the operation doesn't complete.

here is the weird part. 

this error only happens when I have **BOTH Shadow & Light (elvui plugin) and GSE (macro sequencer addon) turned on**. if I turn either one of those off, everything seems to work as expected.  I also deactivated every other addon I have to explicitly narrow down the interaction to these addons.

-a side note- this was a problem before the big 11.02 patch today. I just hadn't gotten around to writing out an issue report.

I get the same error in Talent Tree Tweaks with the same addons enabled, if I try to import something there instead.

I have spoken to the dev of GSE, and he says its something with the talent API just being overworked and there's nothing he can do about it on his end. He suggested I contact you potentially for a fix. 

I use both Shadow and Light and GSE heavily every day, so ideally I would like to be able to use everything together and not turn addons off just to import/change builds. :)

thanks, hope this isn't too complex
I'm in your discord as MechaZao if you need to ping me for any further info or anything 👍

**Comment by Numynum** [comment]
Should be resolved in the next GSE update 👍 
and I _think_ that elvui S&L is reacting to GSE doing its thing, so fixing GSE also resolves the slowdown from S&L hopefully
