### ISSUE TITLE
Not saving talents on a druid

### ISSUE THREAD

**Issue by lqnrd** [NumyAddon/TalentLoadoutManager#22]
Context: Level 70 guardian druid, no loadouts saved (just using the default Blizzard loadout)

1. Start with a clean install of TLM
2. Create a new Blizzard loadout from the default UI (click on dropdown, then "+ New Loadout"), give it a name ("Bliz1")
3. Design some talent tree using wowhead, export: CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZGzs5BGYMmZWMzMMLWAYMDzMzENzMzYmxsMYjBAAAAAAMYAAAAQBAAAw8AzA
4. Using TLM's "Import" button, import this loadout and give it a name "Custom1"
5. Left tree view now shows I'm using the base layout "Bliz1" and my custom layout "Custom1". In the talent tree, change one talent point (I removed one point from "Lore of the Grove" and put it into "Ursine Vigor")
6. "Apply Changes"
7. Now exporting the layout "Custom1" it gives me "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZGzs5BGYMmZWMzMMLWAYMDzMzENzMzYmxsMYjBAAAAAAMYAAAAAAAAAMPwMA", which is exactly the same as the one I exported on wowhead
8. /reload
9. The changes were not saved (exporting the layout "Custom1" still yields CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZGzs5BGYMmZWMzMMLWAYMDzMzENzMzYmxsMYjBAAAAAAMYAAAAAAAAAMPwMA), and clicking on "Custom1" loads the layout that was exported from wowhead earlier.

It seems to only save a layout on importing a layout string, not when changing talents within the game.

This happens to all specs on my druid (I'm just using guardian as an example).

**Comment by Numynum** [comment]
you have to explicitly press the save button; this is partially to avoid destroying the loadout if you use it on a lower level character (as it'd then forget all the talents it couldn't buy)

**Comment by lqnrd** [comment]
i feel dumb now, but thanks for the quick answer :)
