### ISSUE TITLE
Edge case when importing a loadout

### ISSUE THREAD

**Issue by emptyrivers** [NumyAddon/TalentLoadoutManager#24]
It's possible to bamboozle TLM into not allowing you to name a loadout which you're importing:

1. Create a new (non-blizzard) loadout. Ensure that it is the "currently selected custom loadout".
2. Import a loadout copied from icywowdisveinsheadcord. Enable the "Import into currently selected custom loadout" option, and click Import. Allow the talent change to take effect.
3. Create a new (blizzard) loadout, and swap to it.
4. Import another loadout copied from icywowdisveinsheadcord. Notice that you are not given the option to set the custom loadout's name. If you confirm the import, then the custom loadout will be named `*importing into current loadou`.

Issue can be worked around by loading a custom loadout, and then opening the import dialog and unchecking "Import into currently selected custom loadout".

**Comment by Numynum** [comment]
Interesting.. I appreciate the clear steps, should make it much easier to find and fix the problem ^^

**Comment by Numynum** [comment]
fixed in latest release 👍
