### ISSUE TITLE
Error every time I open the talent window

### ISSUE THREAD

**Issue by gotex007** [NumyAddon/TalentLoadoutManager#25]
6x TalentLoadoutManager/modules/SideBarMixin.lua:614: attempt to index global 'TLM' (a nil value)
[string "@TalentLoadoutManager/modules/SideBarMixin.lua"]:614: in function <TalentLoadoutManager/modules/SideBarMixin.lua:613>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:493: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:295: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:174: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:169>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:893: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:871>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:130: in function `TogglePlayerSpellsFrame'
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:165: in function `ToggleClassTalentOrSpecFrame'
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'TLM' (a nil value)"
sideBar = Frame {
 ImportButton = Button {
 }
 Warning = FontString {
 }
 PixelSnapDisabled = true
 ConfigButton = Button {
 }
 SaveButton = Button {
 }
 Title = FontString {
 }
 ScrollBoxContainer = Frame {
 }
 CreateButton = Button {
 }
 ToggleSideBarButton = Button {
 }
 Background = Texture {
 }
}

**Comment by Numynum** [comment]
Fixed in next update ^^
