### ISSUE TITLE
Feature WIP: Talent Tree Leveling Tips

### ISSUE THREAD

**Issue by mateutek** [NumyAddon/TalentLoadoutManager#7]
Hi @Numynum , following the discussion on the TalentTreeTweaks, I've started to work on the feature, but i would love to get some better LUA/WowApi insight. Do you have discord/sth where i can ask you some questions ?

**Comment by Numynum** [comment]
you can add me on discord, username: `.numy`

**Comment by Numynum** [comment]
https://www.curseforge.com/wow/addons/talent-loadout-manager and https://www.curseforge.com/wow/addons/talenttree-viewer now support leveling builds, closing 🙂
